// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['TTTApp']['Close']();
}

export function EditTask(arg1) {
  return window['go']['main']['TTTApp']['EditTask'](arg1);
}

export function EditTasks2(arg1) {
  return window['go']['main']['TTTApp']['EditTasks2'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['TTTApp']['OpenDataFolder']();
}

export function StartTask(arg1) {
  return window['go']['main']['TTTApp']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['TTTApp']['StopTask']();
}

export function TaskState() {
  return window['go']['main']['TTTApp']['TaskState']();
}
