// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ttt} from '../models';
import {main} from '../models';

export function Close():Promise<void>;

export function EditTask(arg1:ttt.TimeEntry):Promise<main.TTTState>;

export function EditTasks2(arg1:Array<ttt.TimeEntryEdit>):Promise<main.TTTState>;

export function OpenDataFolder():Promise<void>;

export function StartTask(arg1:main.StartTaskReq):Promise<main.TTTState>;

export function StopTask():Promise<main.TTTState>;

export function TaskState():Promise<main.TTTState>;
